### ISSUE TITLE
Icons, grid images with links, flex, responsiveness

### ISSUE THREAD

**Issue by Andreatorromeo** [Andreatorromeo/andreatorromeo.github.io#1]
Good morning, @gorazd !
About the Portfolio, I'd like to have only one page with all relative links, except for my section "Projects", which will bring the user to a different page, that's because i don't have enough "career background" to cover more different pages in the website. What do you think about it?

About codes, these are my main issues at the moment:

- CONTACTS ICONS
https://github.com/Andreatorromeo/andreatorromeo.github.io/blob/6a61558ba807c38e77d5d025409beb0c70c7c5e4/index.html#L106-L117
https://github.com/Andreatorromeo/andreatorromeo.github.io/blob/6a61558ba807c38e77d5d025409beb0c70c7c5e4/style.css#L385-L394
In this case i haven't specified the height of the icon in the CSS, but i can see the picture until i insert in the HTML an <a> inside the image, as soon as i insert it, only the right icon disappears.
Plus when visiting the website from the mobile, i can see the pictures not aligned.

- FLEX ON MICROSOFT EDGE IS NOT WORKING
https://github.com/Andreatorromeo/andreatorromeo.github.io/blob/6a61558ba807c38e77d5d025409beb0c70c7c5e4/index.html#L45-L61
https://github.com/Andreatorromeo/andreatorromeo.github.io/blob/6a61558ba807c38e77d5d025409beb0c70c7c5e4/style.css#L226-L231
While on Chrome and Firefox everything is fine, on Edge seems that "space evenly" inside the flex doesn't work.

- GRID IMAGES
https://github.com/Andreatorromeo/andreatorromeo.github.io/blob/6a61558ba807c38e77d5d025409beb0c70c7c5e4/index.html#L93-L97
https://github.com/Andreatorromeo/andreatorromeo.github.io/blob/6a61558ba807c38e77d5d025409beb0c70c7c5e4/style.css#L334-L354
In this case i've two problems, one for the link, one for the pictures.
Those pictures should have the link to redirect on three different project pages.
I've put those images inside the CSS as background-image and not inside the HTML and i feel that this is an error.
But if i do this on the HTML
`<a href="#"><div class="item-1"></div> </a>`
the picture disappear.

While if i do this, the picture doesn't fit the grid anymore
`<div class="item-1"><img src="Images/1"</div>`

-RESPONSIVENESS 
Obviously i'll use mediaqueries, but at the moment if you stretch or shrink the page, you can see how the inclined background changes because it has a `position: absolute` and it's a pseudo-element. Is it going to be a problem?

About hamburger menu,now that you explained to us and now that i'm studing JS i'll try to create it with JS  and not with CSS.

Thank you for your patience and help!

**Comment by gorazd** [comment]
For the contact icons try putting the width and height attributes to the image elements.

**Comment by gorazd** [comment]
For browser support it is good to consult the caniuse.com website.

In the case of flexbox, if you look at the tab _known issues_, the last issue explains your case:
https://caniuse.com/#feat=flexbox

Why not use `justify-content: space-around;` and put either a max-width or left and right magins to div.icons.

**Comment by gorazd** [comment]
For the grid images try this html `<a href="#" class="item-1"></a>`.

The link is now a grid item. In your case `<a href="#"><div class="item-1"></div></a>` the div has no content or width and height properties in the css file. If you inspect it, the width and height are probably 0.

Use the inspector to debug your layout, it makes it easier to understand how the browser behaves.
Microsoft EDGE also has this tool, try it out to see the space-around value.

**Comment by gorazd** [comment]
I don't understand the inclined background change. When I resize the window it looks good.

You could maybe use a linear gradient as the background of each section for more control.

*Please open a different issue for different bugs/questions. This way it's easier to keep track and you can close them as you fix them. 

Thank you!

**Comment by Andreatorromeo** [comment]
Fixed everything, and "everything works" now.
Thank you for your help!
About the icons in the "Contacts" section,  i had to fix more things because i'm an idiot and i made some stupid mistake. Coherence.
Next issues will be splitted
Have a good day!
