### ISSUE TITLE
background problem on mediaquery

### ISSUE THREAD

**Issue by Andreatorromeo** [Andreatorromeo/andreatorromeo.github.io#2]
https://github.com/Andreatorromeo/andreatorromeo.github.io/blob/0af908a0b68c67cd841dd525d2ead9d6905b9f86/style.css#L59-L79

Good evening @gorazd, 
i created the mediaquery for the iphone 8, don't mind the menu etc.
When i see it through the google inspector, it seems fine, but when i see it on an iphone 8, before the dark inclined gray background i have white space and i don't know why. Could you help me to figure it out please?

**Comment by gorazd** [comment]
Hello, could you provide a screenshot of how it should be and how you see it please.

**Comment by Andreatorromeo** [comment]
'Morning, this is how it should be, pay attention to the "ABOUT" "PROJECTS" and "CONTACTS" positioning. 
They are right below the inclined background.
And this should be with all the devices. 

![error](https://user-images.githubusercontent.com/58331527/81056288-960a0b00-8eca-11ea-832c-a056a704d821.jpg)

__
__

The problem is that for every device the inclined background has a different behaviour. And this is what i got when i visit the website using the iphone X, for instance:
__
__

![WhatsApp Image 2020-05-05 at 12 27 52](https://user-images.githubusercontent.com/58331527/81057149-2c8afc00-8ecc-11ea-92a9-b5e4b1b1aa7b.jpeg)
__
That was the real website on the Iphone, but i can't properly work on it because from my desktop, on the Chrome inspector tool everything seems work:

![error2](https://user-images.githubusercontent.com/58331527/81057608-0ade4480-8ecd-11ea-824e-0dd5a2fe20dc.jpg)
__
__
On ipad seems fine until i have it in the wide screen, when i rotate it, the background and titles become even worst than the Iphone X.

**Comment by Andreatorromeo** [comment]
Yessss, your code works! :D
Thank you!

**Comment by gorazd** [comment]
Yeah, but does it make sense?

:))

**Comment by Andreatorromeo** [comment]
It’s a little bit tricky, but yes.
Basically you removed the background section in the html and added an inner wrap of the section which contain everything but the header of the section.

In the CSS the outer section now is in relative position, in this way you created the pseudoelement ”projects:after” with the position in “absolute” so it lt’s bounded to the relative one.
Then you set the inner wrap width.

Nice trick, maybe in 10 years i can think of it by myself :D
