### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by gorazd** [Andreatorromeo/andreatorromeo.github.io#4]
- Add projects
- Add `scroll-behavior: smooth;` to your CSS
- Next project link
- Footer content

**Comment by Andreatorromeo** [comment]
Add projects | DONE
Scroll-behaviour | DONE
Next project link | Done on another html due the complexity of animations
Footer content | Won't be present

**Comment by gorazd** [comment]
The projects link is not working for me.

**Comment by Andreatorromeo** [comment]
Why? I made the three projects links and they works for me

**Comment by gorazd** [comment]
It was taking me to the About section. It works now.
