### ISSUE TITLE
Animation on scrolling

### ISSUE THREAD

**Issue by Andreatorromeo** [Andreatorromeo/andreatorromeo.github.io#5]
Hello @gorazd 
I was working on animations for titles, like "about me, projects" etc. I was wondering if there is a way to activate the animation only when the viewport reaches that element. 
Because at the moment all the animations are triggered on the page loading, so when you scroll down the animation it's already finished.

Thank you

**Comment by gorazd** [comment]
You will need to use a JS library for that:
https://github.com/michalsnik/aos

Or a native solution:
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by Andreatorromeo** [comment]
D: i tried to look on Google how to apply the library and I'm scared to mess up something

**Comment by gorazd** [comment]
OK, we can look at this in the second phase.
