### ISSUE TITLE
Hover Animations on grids element

### ISSUE THREAD

**Issue by Andreatorromeo** [Andreatorromeo/andreatorromeo.github.io#6]
Hello, @gorazd 
Talking of the homepage grid.
https://github.com/Andreatorromeo/andreatorromeo.github.io/blob/29ffc774f084085fbdfec497d85329605a85e91d/index.html#L95-L100

https://github.com/Andreatorromeo/andreatorromeo.github.io/blob/29ffc774f084085fbdfec497d85329605a85e91d/style.css#L301-L304
i tried to apply a zoom on hover using  `transform: scale(1.2);` on a grid child which has a background image. But on hover all the grid child get zoomed and not only the background image.

Do you have any suggestion? 
Thanks

**Comment by gorazd** [comment]
Did you fix this?

**Comment by Andreatorromeo** [comment]
mm nope, the zoom is still not smoothy

**Comment by gorazd** [comment]
Smoothly? What am I a mind reader ;))
The thing is you can't animate background images with `transitions`.

See this example for a working solution and let me know if something is unclear:
https://gorazd.github.io/css-exercises/students/andrea-zoom.html

The file is here:
https://github.com/gorazd/css-exercises/blob/master/students/andrea-zoom.html

**Comment by Andreatorromeo** [comment]
Yeah, the problem is that i have a background image and i wouldn't change the grid again, especially because it's already good for devices too.
What do you think about the actual animation on hover?

**Comment by gorazd** [comment]
I'd say forget the animation for now.

I'd be more worried about semantics.
How do your links look to you:
```
<article class="projects-grid">
  <a href="/magis.html" class="item-1"></a>
  <a href="/thefork.html" class="item-2"></a>
  <a href="/portfolio.html" class="item-3"></a>
  <a href="#" class="item-4"></a>
</article>
```

**Comment by gorazd** [comment]
I meant forget the zoom animation, keep the color transition.
Maybe make it:
- faster
- disable the hover on mobile

**Comment by gorazd** [comment]
To understand how Google sees your page,
try disabling the CSS to see how your site looks and tell me what you think.

https://www.youtube.com/watch?v=hftoly8QhEs

**Comment by Andreatorromeo** [comment]
Uhm, yeah, inside the projects section there is no link.
Is that a problem?

**Comment by gorazd** [comment]
The link is there, only without content.

> Content within each <a> should indicate the link's destination.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

My suggestion is that you put relevant content in the link, example:
`<a href="/magis.html" class="item-1"><span>Magis - Art direction</span></a>`
and then you can decide to hide the text with CSS:
https://www.sitepoint.com/hide-elements-in-css/

**Comment by Andreatorromeo** [comment]
What an error. I deserve to be slapped D:
Thank you so much!
