### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by gorazd** [Andreatorromeo/andreatorromeo.github.io#7]
Please check your image sizes.

On the Magis page I noticed it loading and there is a 7.5MB image:
https://github.com/Andreatorromeo/andreatorromeo.github.io/blob/master/Images/magis/progetto_completo.png

First check how big do you need the images to be.
Then optimise them, if you don't need transparency JPG might be better.

You can use this tool:
https://imageoptim.com/mac

**Comment by Andreatorromeo** [comment]
I optimized all the images.
Portfolio folder= 2.52MB
Thefork folder= 3.96MB
Magis folder= 7.8 MB

Magis sadly has two gif which have to be in a good quality.

**Comment by gorazd** [comment]
What size would the two gifs be in .mp4 format?

**Comment by Andreatorromeo** [comment]
Around 7 MB each

**Comment by gorazd** [comment]
If you figure out the biggest width at which the image will be displayed, you could resize them.

Maximum width of the wrapper minus the width of the other column.
